### ISSUE TITLE
Cinder Volume Migration not working as expected

### ISSUE THREAD

**Issue by zenpwning** [MirantisWorkloadMobility/CloudFerry#1143]
I'm using 2 Single Juno Clouds, where Cinder has both V1 & V2 API Endpoints, it is not showing any errors but It is not migrating volumes even when I mentioned the IDs of Tenant, Instance, Volume in filter.yaml file with the scenario: migrate_resources.yaml [I have created the cinder voulumes using LVM concept without NFS or ISCSI]

@SVilgelm @roman-verchikov @openstackmigration @MirantisWorkloadMobility

**Comment by roman-verchikov** [comment]
LVM cinder backend is not supported, only NFS and iSCSI VMAX are supported.

**Comment by zenpwning** [comment]
But as per your link: https://github.com/roman-verchikov/CloudFerry       The supported cases are listed below. Tool supports any iscsi-like mechanism for Cinder backend as for Cinder service with LVM backend:

1) Source - Cinder (LVM), Glance (file) --> Destination - Cinder (LVM), Glance (file)
2) Source - Cinder & Glance (Ceph) --> Destination - Cinder (LVM), Glance (file)
3) Source - Cinder & Glance (Ceph) and Nova ephemeral volumes (Ceph) --> Destination - Cinder (LVM), Glance (file)
4) Source - Cinder (LVM), Glance (file) --> Destination - Cinder & Glance (Ceph)
5) Source - Cinder (LVM), Glance (file) --> Destination - Cinder & Glance (Ceph) and Nova ephemeral volumes (Ceph)
6) Source - Cinder & Glance (Ceph) --> Destination - Cinder & Glance (Ceph)
7) Source - Cinder & Glance (Ceph) and Nova ephemeral volumes (Ceph) --> Destination - Cinder & Glance (Ceph) and Nova ephemeral volumes (Ceph)

Isn't it contradictory?

**Comment by roman-verchikov** [comment]
The documentation you're looking at is master branch of my personal fork which was not updated since Aug 19, 2015.

**Comment by zenpwning** [comment]
Thanks for the information.
