### ISSUE TITLE
Live Migration Failing

### ISSUE THREAD

**Issue by zenpwning** [MirantisWorkloadMobility/CloudFerry#1146]
**At first when I ran LiveMigration Scenario. I got this error**

INFO     <NoTask> [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:70] 09-04 18:03:00 Processing CHAIN PREPARATION
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:51] 09-04 18:03:00 Start task 'CheckQemuVersion'
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/utils/log.py:47] 09-04 18:03:01 [cloud1] run: kvm -version | sed -E 's/QEMU emulator version ([0-9]\.[0-9]\.?[0-9]?).*/\1/'
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/utils/log.py:47] 09-04 18:03:02 [cloud1] out:
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/utils/log.py:47] 09-04 18:03:02 /bin/bash: kvm: command not found
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/utils/log.py:47] 09-04 18:03:02 [cloud1] out:
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/utils/log.py:47] 09-04 18:03:02 [cloud2] run: kvm -version | sed -E 's/QEMU emulator version ([0-9]\.[0-9]\.?[0-9]?).*/\1/'
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/utils/log.py:47] 09-04 18:03:03 [cloud2] out:
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/utils/log.py:47] 09-04 18:03:03 /bin/bash: kvm: command not found
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/utils/log.py:47] 09-04 18:03:03 [cloud2] out:
ERROR    CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/actions/live_migration/live_migration.py:224] 09-04 18:03:03 qemu must be upgraded to v2.0 on following hosts: [u'cloud1', u'cloud2']
ERROR    CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:60] 09-04 18:03:03 CheckQemuVersion TASK FAILED: qemu must be upgraded to v2.0 on following hosts: [u'cloud1', u'cloud2']
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 73, in process_chain
    self.run_task(task)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 65, in run_task
    self.map_func_task[task](task)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 100, in task_run
    task(namespace=self.namespace)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/task.py", line 96, in __call__
    result = self.run(**namespace.vars)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/actions/live_migration/live_migration.py", line 225, in run
    raise RuntimeError(msg)
RuntimeError: qemu must be upgraded to v2.0 on following hosts: [u'cloud1', u'cloud2']
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:83] 09-04 18:03:03 Failed processing CHAIN PREPARATION
ERROR    CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cliff/app.py:351] 09-04 18:03:03 Migration failed with exit code 1

**===========================================================================**

**I've installed KVM in both of my single node Juno clouds. When I run the command1: "kvm -version". I get the following output:**
`QEMU emulator version 2.0.0 (Debian 2.0.0+dfsg-2ubuntu1.27), Copyright (c) 2003-2008 Fabrice Bellard`

Command2: **"kvm -version | sed -E 's/QEMU emulator version ([0-9]\.[0-9]\.?[0-9]?).*/\1/'"**
`2.0.0`

**After that as I run Live Migration, I'm still facing the following error:**

INFO     <NoTask> [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:70] 09-04 18:15:56 Processing CHAIN PREPARATION
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:51] 09-04 18:15:56 Start task 'CheckQemuVersion'
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/utils/log.py:47] 09-04 18:15:56 [cloud1] run: kvm -version | sed -E 's/QEMU emulator version ([0-9]\.[0-9]\.?[0-9]?).*/\1/'
ERROR    CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:60] 09-04 18:16:13 CheckQemuVersion TASK FAILED: Name lookup failed for cloud1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 73, in process_chain
    self.run_task(task)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 65, in run_task
    self.map_func_task[task](task)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 100, in task_run
    task(namespace=self.namespace)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/task.py", line 96, in __call__
    result = self.run(**namespace.vars)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/actions/live_migration/live_migration.py", line 215, in run
    version = runner.run(qemu_version_cmd)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/utils/remote_runner.py", line 141, in run
    raise RemoteExecutionError(e.message)
RemoteExecutionError: Name lookup failed for cloud1
INFO     CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:83] 09-04 18:16:13 Failed processing CHAIN PREPARATION
ERROR    CheckQemuVersion [/usr/local/lib/python2.7/dist-packages/cliff/app.py:351] 09-04 18:16:13 Migration failed with exit code 1

@SVilgelm @roman-verchikov @openstackmigration @MirantisWorkloadMobility

**Comment by SVilgelm** [comment]
Live migration is not supported.

**Comment by zenpwning** [comment]
@SVilgelm  Live Migration, is it still under development? Or Is it like: Live migration worked before & is not working now?

**Comment by SVilgelm** [comment]
> Live migration worked before & is not working now?

**Comment by zenpwning** [comment]
I mean: Did live migration work before in the previous releases of cloudferry or under any particular conditions?

**Comment by SVilgelm** [comment]
We doesn't support it and it's not working now. Probably it worked some time ago.
