### ISSUE TITLE
No option for USE of resource_map.yaml in config.ini

### ISSUE THREAD

**Issue by zenpwning** [MirantisWorkloadMobility/CloudFerry#1149]
As per the file: [https://github.com/MirantisWorkloadMobility/CloudFerry/blob/master/configs/ext_net_map.yaml](ext_net_map.yaml)

It is says "THIS FILE IS DEPRECATED, USE resource_map.yaml INSTEAD !!"

But I don't find any options for the use of: resource_map.yaml in
[https://github.com/MirantisWorkloadMobility/CloudFerry/blob/master/configs/config.ini](config.ini)

@SVilgelm @roman-verchikov @openstackmigration @MirantisWorkloadMobility

**Comment by SVilgelm** [comment]
You can add `resource_map` option into `[migrate]` section.
```
[migrate]
resource_map=configs/resource_map.yaml
```
