### ISSUE TITLE
Cold Migration Fails at CheckCloud stage while Migration of resources & VMs work fine

### ISSUE THREAD

**Issue by zenpwning** [MirantisWorkloadMobility/CloudFerry#1152]
**Cold Migration Fails at CheckCloud stage while Migration of resources & VMs work fine**
As per @roman-verchikov suggestion I've added "service_tenant" field in both Src & Dst options.

I'm getting the following warning Object "tenant" with name "fdb8479818a0455e8bc6a97f367de52b" not found. I've checked my clouds I dont have any project[tenant] with that ID.

My Configuration file: [configuration.ini](http://pastebin.com/GnBwx7F6)

INFO     CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:51] 09-16 10:27:40 Start task 'CheckCloud'
INFO     CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/actions/prechecks/check_cloud.py:46] 09-16 10:27:40 Creating tenant 'tenant_1474021660'...
INFO     CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/actions/prechecks/check_cloud.py:96] 09-16 10:27:40 Creating image 'image_1474021660'...
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:54] 09-16 10:27:52 Waiting for status change
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:64] 09-16 10:27:52 Expected status is 'active', actual - 'active', stop statuses - ['error']
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:71] 09-16 10:27:52 Expected status reached, exit
INFO     CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/actions/prechecks/check_cloud.py:72] 09-16 10:27:52 Creating network 'shared_net_1474021660'...
INFO     CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/actions/prechecks/check_cloud.py:72] 09-16 10:27:53 Creating network 'private_net_1474021660'...
INFO     CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/actions/prechecks/check_cloud.py:106] 09-16 10:27:54 Creating volume 'volume_1474021660'...
**WARNING  CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/os/identity/keystone.py:833] 09-16 10:27:54 Object "tenant" with name "fdb8479818a0455e8bc6a97f367de52b" not found**
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:54] 09-16 10:27:57 Waiting for status change
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:64] 09-16 10:27:58 Expected status is 'available', actual - 'creating', stop statuses - ['error']
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:74] 09-16 10:27:58 Expected status NOT reached, waiting
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:64] 09-16 10:27:59 Expected status is 'available', actual - 'creating', stop statuses - ['error']
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:74] 09-16 10:27:59 Expected status NOT reached, waiting
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:64] 09-16 10:28:02 Expected status is 'available', actual - 'creating', stop statuses - ['error']
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:74] 09-16 10:28:02 Expected status NOT reached, waiting
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:64] 09-16 10:28:07 Expected status is 'available', actual - 'creating', stop statuses - ['error']
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:74] 09-16 10:28:07 Expected status NOT reached, waiting
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:64] 09-16 10:28:16 Expected status is 'available', actual - 'error', stop statuses - ['error']
DEBUG    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py:66] 09-16 10:28:16 Stop status reached, exit
INFO     CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/actions/prechecks/check_cloud.py:79] 09-16 10:28:16 Deleting previously created network 'private_net_1474021660'...
INFO     CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/actions/prechecks/check_cloud.py:79] 09-16 10:28:17 Deleting previously created network 'shared_net_1474021660'...
INFO     CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/actions/prechecks/check_cloud.py:101] 09-16 10:28:17 Deleting previously created image 'image_1474021660'...
INFO     CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/actions/prechecks/check_cloud.py:57] 09-16 10:28:35 Deleting previously created tenant 'tenant_1474021660'...
ERROR    CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:60] 09-16 10:28:36 CheckCloud TASK FAILED:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 73, in process_chain
    self.run_task(task)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 65, in run_task
    self.map_func_task[task](task)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py", line 100, in task_run
    task(namespace=self.namespace)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/task.py", line 96, in __call__
    result = self.run(**namespace.vars)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/actions/prechecks/check_cloud.py", line 215, in run
    self.create_volume(cn_client, volume_info):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/actions/prechecks/check_cloud.py", line 110, in create_volume
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/cloudferry/lib/base/resource.py", line 69, in wait_for_status
    wait_status, "Timed out waiting for state change")
TimeoutException
INFO     CheckCloud [/usr/local/lib/python2.7/dist-packages/cloudferry/lib/scheduler/scheduler.py:83] 09-16 10:28:36 Failed processing CHAIN PREPARATION
ERROR    CheckCloud [/usr/local/lib/python2.7/dist-packages/cliff/app.py:349] 09-16 10:28:36 Migration failed with exit code 1

@roman-verchikov @MirantisWorkloadMobility @openstackmigration @SVilgelm

**Comment by roman-verchikov** [comment]
cinder volume creation timed out in destination cloud, either you have problems in cloud, or you need to increase wait time with `[migrate] storage_backend_timeout`

**Comment by zenpwning** [comment]
In my test setup, there is no cinder service so I've tried in the following ways
1. testing migration by commenting out the storage section in configuration.ini
2. above case + testing migration by commenting out the storage & volume lines in the file: **scenario/cold_migrate.yaml**

But in both the cases I'm facing above error.
