### ISSUE TITLE
No options in src & dst for Availability zone

### ISSUE THREAD

**Issue by zenpwning** [MirantisWorkloadMobility/CloudFerry#1157]
Availability zone to use for VM provisioning, in case source cloud zones do not match destination
**default_availability_zone = nova**

I don't see any options in source & destination for Availability zone, in configuration files. Is it mandatory for the source and destination availability zones to match(to be same)?

@roman-verchikov @SVilgelm @MirantisWorkloadMobility @openstackmigration

**Comment by roman-verchikov** [comment]
You can map availability zones in `configs/override_rules.yaml`, examples are available in https://github.com/MirantisWorkloadMobility/CloudFerry/blob/master/configs/override_rules.yaml. When you change `override_rules.yaml` file, make sure it is configured in your primary configuration file in `[migrate] overrider_rules` option.
