### ISSUE TITLE
fuel6.1 no deployment mode

### ISSUE THREAD

**Issue by yutinghgx** [MirantisWorkloadMobility/CloudFerry#259]
Hello;
I have installed the fuel6.1 ,when i create a envirement ,there is no deployment node menu.After i have installed the envirement,the defalt deployment node is HA mode.How to do it?

**Comment by akolodyazhnyy** [comment]
Hi,

please note, that there is only HA mode for controllers in Fuel 6.1 left. Basically, when you install one controller, it is deployed with all HA features anyway, but they are pointed to this node only.
Also, this is migration tool repo, and this is not an appropriate place to ask questions related to Fuel or MOS. If you have any other questions, you can ask them in #fuel IRC channel.

**Comment by yutinghgx** [comment]
OK,I see, thanks very much!!!

**Comment by akolodyazhnyy** [comment]
You're welcome!
